// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// GENERATED by `make biomes` (scripts/biome-preview.mjs). Do not edit.
//
// WHAT EACH BIOME BANNER IS A PICTURE OF. The banners themselves are JPEGs
// under pwa/public/previews/, rendered by the real game from a camera over
// the country's FIRST campaign stage — so what they show depends entirely on
// that level's seed, band, shape and conditions.
//
// Nothing at runtime reads this. It exists because a photograph cannot be
// recomputed and compared the way a route can: without it, editing a
// country's first stage leaves a banner of a road nobody drives, in weather
// the stage is no longer set in, and NOTHING anywhere would say so.
// tests/stage_preview_test.ts holds this against campaign.ts.

export type BiomeShot = {
  /** The campaign level the camera stood on the start line of. */
  level: string;
  seed: number;
  length: string;
  shape: string;
  timeOfDay: string;
  weather: string;
  season: string;
};

export const BIOME_SHOTS: Record<string, BiomeShot> = {
  taiga: {
    level: "taiga-1",
    seed: 38,
    length: "short",
    shape: "sprint",
    timeOfDay: "day",
    weather: "clear",
    season: "summer",
  },
  desert: {
    level: "desert-1",
    seed: 16,
    length: "short",
    shape: "sprint",
    timeOfDay: "day",
    weather: "clear",
    season: "summer",
  },
};
