// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// THE MODEL REGISTRY: every kind of object the game draws, and whether what
// the player sees is a MODEL made in Blender (`make models`, committed in
// `pwa/models/`, the `blender-assets` skill) or GENERATED by the game's own
// code at run time. One row an asset: its ids, where each half lives and
// the switch that sends a modelled asset back to its code.
//
// A modelled asset keeps its code builder — the switch's other side, and
// what the model is judged against — so every row names one. The road, the
// terrain and its water, the sky and the weather, the dust, the spray, the
// tyre tracks and the snow's marks are surfaces and effects, not objects,
// and are not rows.
//
// `tests/model_registry_test.ts` holds it to the tree: the Blender rows'
// files are exactly the files the build packs (`modelFiles`), every path
// named here exists, and `docs/models.md` carries `renderModelRegistry()`
// (`make model-registry` rewrites it, and prettier pads its columns).
// DOM-free and three-free.

import { CARS, TRAFFIC_MODELS } from "@engine";

import { BIOMES } from "./biome.ts";
import { CREW_IDS } from "./car-crew.ts";
import { TREE_ROW, TREE_ROWS } from "./flora-tree-rows.ts";
import { PLANT_KIND_LIST, TREE_KINDS, floraModelFile } from "./flora-trees.ts";
import { WOODEN_PROPS } from "./planting.ts";
import { propModelFile } from "./prop-kinds.ts";
import { PROP_KINDS } from "./prop-models.ts";

export type ModelSource = "blender" | "code";

export type ModelRow = {
  /** What is drawn, in the player's words. */
  asset: string;
  /** Every id of it the game draws. */
  ids: readonly string[];
  /** Where the drawn geometry comes from today. */
  source: ModelSource;
  /** The code that builds it — the only builder of a `code` row, the
   * switched-off one of a `blender` row. */
  code: readonly string[];
  /** What puts it in the scene. */
  drawnBy: string;
  /** A modelled asset's Blender builder, its committed files (published
   * names under `pwa/models/`, and their shape as one pattern), and the
   * build switch that turns it back. */
  blender?: { builder: string; files: readonly string[]; pattern: string; switch: string };
  /** Anything a reader should know that the columns do not say. */
  note?: string;
};

const CAR_IDS = CARS.map((c) => c.id);

/** Every flora id a biome plants that is not a tree — read off the biomes'
 * own MIXES (`FloraMix`, id → weight: a community's `trees` and
 * `undergrowth`, a biome's shore, bank, highland and verge mixes), wherever
 * in a biome's row they sit. */
function undergrowth(): string[] {
  const ids = new Set<string>();
  const MIX = /^(trees|undergrowth)$|Trees$|Cover$/;
  const walk = (o: unknown): void => {
    if (!o || typeof o !== "object") return;
    for (const [k, v] of Object.entries(o)) {
      if (MIX.test(k) && v && typeof v === "object") {
        for (const id of Object.keys(v)) if (!(id in TREE_ROW)) ids.add(id);
      } else walk(v);
    }
  };
  for (const b of Object.values(BIOMES)) walk(b);
  return [...ids].sort();
}

/** The flora recipes, where every plant — tree or not — is built in code. */
const FLORA_CODE = [
  "pwa/src/game/flora-species.ts",
  "pwa/src/game/flora-alpine.ts",
  "pwa/src/game/flora-desert.ts",
  "pwa/src/game/flora-build.ts",
];

export const MODEL_REGISTRY: readonly ModelRow[] = [
  {
    asset: "Cars",
    ids: CAR_IDS,
    source: "blender",
    code: ["pwa/src/game/car-body.ts", "pwa/src/game/car-styles.ts", "pwa/src/game/car/shell.ts"],
    drawnBy: "pwa/src/game/car-models.ts",
    blender: {
      builder: "scripts/blender/car.py",
      files: CAR_IDS.map((id) => `${id}.glb`),
      pattern: "<id>.glb",
      switch: "VITE_MODEL_CARS",
    },
    note:
      "poured into the code-built car part for part: the model carries the forms (the shell, " +
      "the bolt-ons, the wheels), the code keeps the livery, the lamps, the glass and the cabin, " +
      "and the damage acts on the model's own meshes",
  },
  {
    asset: "Trees",
    ids: TREE_KINDS,
    source: "blender",
    code: FLORA_CODE,
    drawnBy: "pwa/src/game/flora.ts",
    blender: {
      builder: "scripts/blender/tree.py",
      files: TREE_KINDS.map((k) => `trees/${k}.glb`),
      pattern: "trees/<kind>.glb",
      switch: "VITE_MODEL_TREES",
    },
    note: `${TREE_ROWS.length} variants, each a full tree and a far sketch for the wild, dressed in the season's paint`,
  },
  {
    asset: "The crew",
    ids: CREW_IDS,
    source: "code",
    code: ["pwa/src/game/car/crew.ts", "pwa/src/game/car-crew.ts"],
    drawnBy: "pwa/src/game/car/interior.ts",
    note: "the driver and the co-driver behind the glass",
  },
  {
    asset: "Undergrowth: shrubs, ground cover, reeds, cacti and flowers",
    ids: undergrowth(),
    source: "blender",
    code: FLORA_CODE,
    drawnBy: "pwa/src/game/flora.ts",
    blender: {
      builder: "scripts/blender/plant.py",
      files: PLANT_KIND_LIST.filter((k) => k !== "deadwood").map(floraModelFile),
      pattern: "flora/<kind>.glb",
      switch: "VITE_MODEL_TREES",
    },
    note: `${PLANT_KIND_LIST.filter((k) => k !== "deadwood").length} kinds, each plant a full model and a far sketch for the wild, dressed in the season's paint as the trees are`,
  },
  {
    asset: "Dead wood and cut timber",
    ids: Object.values(WOODEN_PROPS).filter((id): id is string => !!id),
    source: "blender",
    code: ["pwa/src/game/flora-species.ts"],
    drawnBy: "pwa/src/game/planting.ts",
    blender: {
      builder: "scripts/blender/plant.py",
      files: [floraModelFile("deadwood")],
      pattern: "flora/deadwood.glb",
      switch: "VITE_MODEL_TREES",
    },
    note: "the engine's wooden solids, drawn to their collision circles",
  },
  {
    asset: "Stone: boulders, rocks and outcrops",
    ids: ["boulder", "rock", "slab"],
    source: "blender",
    code: ["pwa/src/game/wild.ts"],
    drawnBy: "pwa/src/game/wild.ts",
    blender: {
      builder: "scripts/blender/prop.py",
      files: [propModelFile("stone")],
      pattern: "props/stone.glb",
      switch: "VITE_MODEL_PROPS",
    },
    note: "one faceted lump, seated and scaled by the wild into each of its three kinds",
  },
  {
    asset: "Traffic",
    ids: TRAFFIC_MODELS.map((m) => m.id),
    source: "blender",
    code: ["pwa/src/game/traffic-fleet.ts"],
    drawnBy: "pwa/src/game/traffic.ts",
    blender: {
      builder: "scripts/blender/prop.py",
      files: [propModelFile("traffic")],
      pattern: "props/traffic.glb",
      switch: "VITE_MODEL_PROPS",
    },
    note: "dressed in each vehicle's own paint by role; the speed signs are the roadside's",
  },
  {
    asset: "Parked cars",
    ids: ["hatch", "saloon", "estate", "van", "pickup"],
    source: "code",
    code: ["pwa/src/game/parked-car.ts"],
    drawnBy: "pwa/src/game/carpark.ts",
    note: "a dozen boxes a car, its length, width and height rolled per car, never the catalog's builder",
  },
  {
    asset: "Houses, homesteads and towns",
    ids: ["house", "chalet", "villa", "apartments", "grocery", "post", "workshop", "barn", "silo"],
    source: "code",
    code: [
      "pwa/src/game/house.ts",
      "pwa/src/game/chalet.ts",
      "pwa/src/game/barn.ts",
      "pwa/src/game/building.ts",
    ],
    drawnBy: "pwa/src/game/world.ts",
  },
  {
    asset: "Farms: the gear, the bales and the livestock",
    ids: [...PROP_KINDS.farm, ...PROP_KINDS.livestock],
    source: "blender",
    code: ["pwa/src/game/farm-gear.ts", "pwa/src/game/livestock.ts"],
    drawnBy: "pwa/src/game/homestead.ts",
    blender: {
      builder: "scripts/blender/prop.py",
      files: [propModelFile("farm"), propModelFile("livestock")],
      pattern: "props/{farm,livestock}.glb",
      switch: "VITE_MODEL_PROPS",
    },
    note: "a tractor in its roll's paint; a breed in each of its two poses",
  },
  {
    asset: "Farms: fences and fields",
    ids: ["fence", "field", "meadow"],
    source: "code",
    code: ["pwa/src/game/paddock.ts"],
    drawnBy: "pwa/src/game/homestead.ts",
    note: "built in world space along each paddock's own rectangle",
  },
  {
    asset: "Energy: the turbines' nacelles and rotors, the solar tables and cabins",
    ids: PROP_KINDS.energy,
    source: "blender",
    code: ["pwa/src/game/wind-farm.ts", "pwa/src/game/solar-farm.ts"],
    drawnBy: "pwa/src/game/world.ts",
    blender: {
      builder: "scripts/blender/prop.py",
      files: [propModelFile("energy")],
      pattern: "props/energy.glb",
      switch: "VITE_MODEL_PROPS",
    },
    note: "the rotor modelled at one diameter and scaled to each farm's",
  },
  {
    asset: "Energy: turbine towers and power lines",
    ids: ["tower", "pylon", "pylon-angle"],
    source: "code",
    code: ["pwa/src/game/wind-farm.ts", "pwa/src/game/powerline.ts"],
    drawnBy: "pwa/src/game/world.ts",
    note: "a tower is its farm's own hub height, a pylon footed leg by leg on the terrain",
  },
  {
    asset: "The train",
    ids: PROP_KINDS.train,
    source: "blender",
    code: ["pwa/src/game/train.ts"],
    drawnBy: "pwa/src/game/train.ts",
    blender: {
      builder: "scripts/blender/prop.py",
      files: [propModelFile("train")],
      pattern: "props/train.glb",
      switch: "VITE_MODEL_PROPS",
    },
  },
  {
    asset: "The railway",
    ids: ["track", "crossing"],
    source: "code",
    code: ["pwa/src/game/railway.ts"],
    drawnBy: "pwa/src/game/world.ts",
    note: "swept along the line",
  },
  {
    asset: "Tunnels and culverts",
    ids: ["tunnel", "culvert"],
    source: "code",
    code: ["pwa/src/game/tunnel.ts", "pwa/src/game/tunnel-lid.ts", "pwa/src/game/culvert.ts"],
    drawnBy: "pwa/src/game/world.ts",
  },
  {
    asset: "Roadside: marker posts and cones",
    ids: PROP_KINDS.roadside,
    source: "blender",
    code: ["pwa/src/game/kerbs.ts", "pwa/src/game/cones.ts"],
    drawnBy: "pwa/src/game/world.ts",
    blender: {
      builder: "scripts/blender/prop.py",
      files: [propModelFile("roadside")],
      pattern: "props/roadside.glb",
      switch: "VITE_MODEL_PROPS",
    },
  },
  {
    asset: "Roadside: split boards, the start and finish gates, and signs",
    ids: ["split-board", "start-gate", "finish-gate", "speed-sign"],
    source: "code",
    code: [
      "pwa/src/game/split-board.ts",
      "pwa/src/game/finish-gate.ts",
      "pwa/src/game/gate-furniture.ts",
      "pwa/src/game/traffic.ts",
    ],
    drawnBy: "pwa/src/game/world.ts",
    note: "each built to its own road's width and footed on the terrain",
  },
  {
    asset: "Spectators",
    ids: PROP_KINDS.crowd,
    source: "blender",
    code: ["pwa/src/game/crowd.ts"],
    drawnBy: "pwa/src/game/world.ts",
    blender: {
      builder: "scripts/blender/prop.py",
      files: [propModelFile("crowd")],
      pattern: "props/crowd.glb",
      switch: "VITE_MODEL_PROPS",
    },
    note: "one figure's four parts, instanced by the hundred and tinted per person",
  },
  {
    asset: "Birds and aircraft",
    ids: ["flock", "raptor", "skein", "airliner"],
    source: "code",
    code: ["pwa/src/game/ambient-life.ts", "pwa/src/game/raptor.ts", "pwa/src/game/skein.ts"],
    drawnBy: "pwa/src/game/ambient-life.ts",
  },
];

const cell = (s: string): string => s.replaceAll("|", "\\|");
const paths = (ps: readonly string[]): string => ps.map((p) => `\`${p}\``).join(", ");

/** The registry as the markdown table `docs/models.md` carries. */
export function renderModelRegistry(rows: readonly ModelRow[] = MODEL_REGISTRY): string {
  const head = [
    "| Asset | Source | Kinds | Blender builder | Committed models | Code builder | Drawn by | Switch |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
  ];
  const body = rows.map((r) => {
    const b = r.blender;
    const models = b ? `${b.files.length} × \`pwa/models/${b.pattern}\`` : "—";
    return `| ${[
      r.asset + (r.note ? ` (${r.note})` : ""),
      r.source === "blender" ? "**Blender**" : "code",
      `${r.ids.length}: ${r.ids.join(", ")}`,
      b ? `\`${b.builder}\`` : "—",
      models,
      paths(r.code),
      `\`${r.drawnBy}\``,
      b ? `\`${b.switch}=0\`` : "—",
    ]
      .map(cell)
      .join(" | ")} |`;
  });
  return [...head, ...body].join("\n");
}

/** The markers the table stands between in `docs/models.md`. */
export const REGISTRY_BEGIN = "<!-- model-registry:begin (make model-registry) -->";
export const REGISTRY_END = "<!-- model-registry:end -->";

/** The table between the markers in `page`. */
export function registryTableIn(page: string): string {
  const a = page.indexOf(REGISTRY_BEGIN);
  const b = page.indexOf(REGISTRY_END);
  if (a < 0 || b < a) throw new Error("docs/models.md has lost its registry markers");
  return page.slice(a + REGISTRY_BEGIN.length, b);
}

/** Two tables that say the same thing, whatever the padding in their cells
 * (prettier aligns the page's columns; the renderer does not). */
export function sameTable(a: string, b: string): boolean {
  const norm = (t: string): string =>
    t
      .split("\n")
      .map((l) =>
        l
          .trim()
          .replace(/\s*\|\s*/g, "|")
          .replace(/-{3,}/g, "---"),
      )
      .filter(Boolean)
      .join("\n");
  return norm(a) === norm(b);
}

/** `page` with the text between the markers replaced by `table`. */
export function withRegistryTable(page: string, table: string): string {
  const a = page.indexOf(REGISTRY_BEGIN);
  const b = page.indexOf(REGISTRY_END);
  if (a < 0 || b < a) throw new Error("docs/models.md has lost its registry markers");
  return `${page.slice(0, a + REGISTRY_BEGIN.length)}\n\n${table}\n\n${page.slice(b)}`;
}
