// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// GENERATED by `make routes` (scripts/stage-routes.mjs). Do not edit.
//
// Every campaign stage's route, as the campaign menu draws it: the compiled
// centreline, simplified to within a pixel and quantised to a byte a
// coordinate. It is here as source rather than as a file to fetch because
// the whole campaign fits in a few kilobytes — cheaper to bundle than to
// ask the network for while a menu is already on screen.
//
// Regenerate whenever the generator's rules move: a stale route is a
// picture of a road nobody drives any more.

export type StageRoute = {
  /** The polyline, base64 of (x, y) byte pairs. 0 is the west and north
   * edge of the route's own bounding box, 255 the east and south. */
  d: string;
  /** How much wider than tall that bounding box is, in the world — what
   * the menu fits its drawing box to, so a stage keeps its shape. */
  aspect: number;
  /** THE ROAD THIS WAS DRAWN FROM. Nothing at runtime reads it; it is the
   * receipt, and `tests/stage_preview_test.ts` holds it against
   * `campaign.ts`. A level's seed or band edited without a
   * `make previews` leaves a picture of the road that USED to be there,
   * under the name of the one that is — and that is invisible unless the
   * data says which road it drew. */
  spec: { seed: number; length: string; shape: string };
};

export const STAGE_ROUTES: Record<string, StageRoute> = {
  "taiga-1": {
    d: "7v7uxey/57bmr+io/oP+evly83DAZblhqVGhT5pPk1OOWopjh2eAaHlmc2JvXW5XbktsR2hDYD9SP0o+Qjo8MzouOyc9IkMaRRREDkAJOwY2BCgIIAgZBhEBDAAGAgIFAAsBETNu",
    aspect: 0.9681,
    spec: { seed: 38, length: "short", shape: "sprint" },
  },
  "taiga-2": {
    d: "/6P/ifd8+Hj9cf1t+2r2Z/Fn23HUcs5xu2q5aMFPxUvMR89Ez0HOPM840TbZM9wv2SPWIM8czBTJEsUSvhe4GKMMnwqcC5MPig+DDIAFfgJ5AHUBcQNtCV8SXhZdHlMzUDdHPEVARkRJRmJIakZvR3FKck5tVWxba15oX1RfTFxIXERdPWMwYy5kLmg9eD17NoI1jCyTKZ0knxudFp8ToxSqEq4PsAezBLgDvgzHDs8A/w==",
    aspect: 0.8793,
    spec: { seed: 19, length: "medium", shape: "sprint" },
  },
  "taiga-3": {
    d: "/0T/If0a+RbyFOsW5xvdLNsu2C/ULMQSugiwAKsCpQGiA50QnhSwH7UbuRq+IMQhxyTIKcYuuDy3P7hCx1HHU8ZXv1+7arlst2ypYqRjoWybcJlzmXmchJuGl4qTi4+Ken13fXaAdoZ0iXKLbYtqjmmRaJhlm2OcXpxbnlqiWahhyGTMbdNx1HXRgruJtI2rkKqVrJmsnaWjoaeXsZOzlLaZs6K0qLesva6/s7+9uMO1yLfeteKy45vimd+RxI7BisCHxYTgg+OA5XvkdOhx52zjaeNh6l/0XfhT/lH/TPxI90XjQt0zzjDNK9AozxnDF70csxyuGawTqw+oAZEAiwKEB4EMghSKGIscih6HJ3AqbixtMW4zcy2KLpAxlDSVOJRKhU5/T3hPcktsSmlNWk9ZUlpVY1lmZWVnY1Mr",
    aspect: 1.3246,
    spec: { seed: 21, length: "long", shape: "sprint" },
  },
  "taiga-4": {
    d: "ppincahtsWKzYrVltmu0fbaRr66wt7K6tLm3r7mtvLC9vMDAwcDGu9K41LTXltaD13zZedx53nfjaepn7Gjube507ITslOqb5qThvuPG49Pl1unZ7ODs5urt6fTr+u389vP46Prl/eT/3f6++a/3qvSo8qzuyezK68rpxemq6qjvpPGb9pP3ivh/9XH0YfBU7lLrU+lZ51rhUOBc3WDbX9da01zOWcpcyFzGV8M8wy3CKMAmuya5K7gyuT23RLRFsD+uQKxFqkWnQKQ+ozqjMaYppyOmHKQYmCGXJJoymjyPT41Pi0qHJoYDhACCAn8MfA15EncScg1pEGcVZR9jIGAdXSBWPlU+UDhNOEo9Rks8VTlTN0w1JjMfMR4vHi0mLUQvVTJcMWUvZitlKGYlYiNiHnAbchlwFmkUaBFrDHkJcQdxBnMEfgGDAIkBjQOSBpsIngqeFJMWlxWpD7YOwRDKE80W0xnUG9cb3xflFuoY/Rr/HP0e8CDrI+sm8CjvKeor2SzUMc4yxiOO",
    aspect: 2.7697,
    spec: { seed: 5, length: "xlong", shape: "sprint" },
  },
  "taiga-5": {
    d: "QaxBfUB5PHU2cRttE2kOZQxfDVkRVB1LIEYgQR47GjcJLwQrACYAIAYaEBYbFDAVPRRND1wFZAJyAIABiQWRCpURlRiPIHsqcDRhS2BRYlZmW21fgGWJaY1uk3icfqiCwYbJiNGN1ZHYltqq3bLmvPnH/s3/0/7Y+d7z4urm0uu066nsn++N+Hr9a/9b/zL4KfQn8SfuKeo73EDWQdFBrQ==",
    aspect: 0.5399,
    spec: { seed: 3, length: "medium", shape: "circuit" },
  },
  "taiga-6": {
    d: "4q3ig+CA3X3QesJ7uH6qhqCIlIaMf3VdcldyUnNMd0aRKpQikxqPEYoMgwl3B2sBZABdA0sWShtNIE4jTSdKKkAuMC8oNCM8JEYiTAJvAHQBeAV7OI86kjqePKA+oUmiUaZUrFS0T7pGv0LCQMhCzEjRYNZt23bkfPGA9IX2jfeq9a/3t/3A//fy/PD/6/3l6dbjzuLI4q4=",
    aspect: 0.729,
    spec: { seed: 6, length: "long", shape: "circuit" },
  },
  "desert-1": {
    d: "1v7Wwdm13q3kqOqn/Kf+pv+k+nzvcutk6F/kXOBa21rSXMpaxVTASLlDskKrRaVMlHeWe5x+oIGmjKeSm6KXpJSjj56MkoWLg4aGWYRSZkNgQ1RHTkZJRAAA",
    aspect: 1.0966,
    spec: { seed: 16, length: "short", shape: "sprint" },
  },
  "desert-2": {
    d: "APkA2gPVB9ML0xTWI9Mm0yjWJ90p4y3lOug/70XyXuhj6WfvbPGF7Ifrh+iC3oLahNaL05LUm9Sg16HdnOWb7ZP2k/mX/LD/t/29977wvOXC3sXYx9XQ09XO2szhzebS6dTu0/HQ88zwxfHB87/7uv+z/q77pvqc95fzlOmU5JLhi+SB433fetJ3znTMcM1ozmbRZd1m32PfYNhbzlnGU7VVqVCOTIxKkEKYQJw8nzaeLaApoyepJ68ssi3OLNkW2RLUDZ4A",
    aspect: 0.9408,
    spec: { seed: 13, length: "medium", shape: "sprint" },
  },
  "desert-3": {
    d: "n/+f46DfpNmw0rHQsM6fw57Bnr6nuLmwxKrcmd2V147XiduF34Xmh+uE7H/reOt0/V7/WP5S+k71TehS51TnV+xb7l/tY+xm6Gnkaddk0mTNZctoymvMcsx1x3m/e7J3rHiqfauEqoiijp6WmpiDlH+Seo14g3J/a39hhVyEWYJUe1R4VnZucXRxe3WAdYVxiGiQZJJhlF2TWo1ViU2DS3tNdkxySG0/bT1vO3U6eTd8L34sgyuJLYwwkDaWOpc/lEiWUKBcpF2oXaxZskS0QbhCu0W7SLhQuVO9U8NSyVLOUNNB3DngNOYv8RvyFO4O6AvfDc4JyQrAEbMQsRCxErIWux2+JsApxinKJM4j0STUJ9MsyTzFPcI8vDS2Ma8woDScM5kxliyXJ5okoyClHaUaoxabE5YLkQmMCogOhxKIGoUfgCJ4InQkciZwLWwxZzJbLlYqUiVNC0sGRAFAADwBKBEmFCgvLjcwPTBBLUkqSyJLHk0AfA==",
    aspect: 0.9712,
    spec: { seed: 11, length: "long", shape: "sprint" },
  },
  "desert-4": {
    d: "Kv8q5SbdJdcn0y7SMsMzvy+7LboqvSi9ILYesBmrG6AXmBmVIZcjliSTI4wnhieBJX8WeRGBEYQWhxSNC5AJlQaXApYAkgOAB30ObAtkDWARXRddG1wfUCFOK08tUy1rLm4wbzdtOm87dDh9OYQ7hT6CQ4JGgE5zTGpQZ1NiVmJZZVtqXHpZflmBXYdgiGOFaHxreXJ4dW93bXxtgGaEZolrjmmTYJNXkFCSSpZJnESiRKlCskS2SrVQr1WwXa9nsmi1Y7hjxG3GbchryGnCYsFavlO+T8NKzTfRNtc62jfgKeAn3CXcIeEa4wrmAugA6gD5CfoN+hT9Gv4d/CD0I/Mi8h7vHOga5h3nI+0o7i3qNeM54UDcRdxI3k3kUOdW61vrX+ls527kbeJr32PdYthj1F3RXM5dzWDOb89x03HWctp93H/hgOOF6Inriu+H/Yz8kfaV8Z30qfut/bP7uvvD98j1zfHW8tn32fnb/+P/5f7n+efy7uru5vbk99/03vPe8OHq3+XFzg==",
    aspect: 1.3106,
    spec: { seed: 30, length: "xlong", shape: "sprint" },
  },
  "desert-5": {
    d: "AMMAhgOBBn4WeBtzHm8haSFjG1MbSB1CIT0sNTUyPzFKM1g6XjpkOXAyeSSAH4sbmx6iHKoXsAu2Br8ByADOAtUG2ArcFeEc9Sv4Mf9L/k/6Ut9d1l/PXcBVq1OlUJtHlUaQRkJkPmk+ble1WLxXw1TKT9EZ/RH/C/4F+gH1APAAxA==",
    aspect: 0.9375,
    spec: { seed: 27, length: "medium", shape: "circuit" },
  },
  "desert-6": {
    d: "IKIgdB1wFG8QbQlmB18JVglRB0wCRAA7AzMJLhAsHC4jKSYjKgYtAzAANgE+B0YKTQlWAlwAZAJrCnAMdwuAB4gIjguSEZMYkSKSJ5QtmTKgNco70T/YSt5N5U3vSfVK/E//V/5d/GHhguGH5pHmmN2j2bLRu83Ay8jL08nau/K096z3ofCY7pDxiPuB/3v/cfxl/139WPhW8FjoX+Bh2lzGWcFRuke4QboryCTIIsUgwiCj",
    aspect: 1.0495,
    spec: { seed: 23, length: "long", shape: "circuit" },
  },
  "alpine-1": {
    d: "AH8ATgRFCj4XOR04Kjo5Nj83SDxRPVo6ZTN2MXwufymDB4UDiwCTAKQIpwypEKgUpBylIqkmsyu4L8lWy1jSW9xZ4lnoXOxf72T1hfeI/Y7/kv2Z9p/toOGe25/UotCnxf8=",
    aspect: 0.7561,
    spec: { seed: 17, length: "short", shape: "sprint" },
  },
  "alpine-2": {
    d: "xzfHFsgPzgfbAN0D5xzsIfMj9ib3M/07/0H8T/pQ803vTulS5lLfTtxO2VHXV9xk4GfmZOlk7Gnsb+d15XzigN6A1HvPfcuByIvFjsGOvou8frh5snmtf6qBp4CkfqB2nWKZW5JYhlp9VXhYdWJxZmxmY1xeW1peWWlUb1BvSGo7bTJrLm4odyJ6HngachZxE3MQeQN+AIIBiQWNEokWih+QN5A6kjyUPpk8pT2qQa9NsE+xULNPwVLJVctZzWPKaMuQ/w==",
    aspect: 1.2452,
    spec: { seed: 27, length: "medium", shape: "sprint" },
  },
  "alpine-3": {
    d: "Of855jviQd5D2z7PRsdGxD+9P7I8rAF7AHcFbQdrGWUiaiZvLHEzejOBNYRAiUiVU5dWnluiY65psmq2Z71owWzDdMZ2yHfNedCE0ojaj9ub2Kfcsdi42L3bz+fU4d/e5d7s4PDf8t331fXS79Pp0eDH4MXiv9624q7hp+Oj6qDrm+iX4JXejdyK2InRic6HzIPNfM9503jpffB9/XX/c/9v/Gv4auZz5HPicuFj32DcXtRfz1zOWdBSz068P7s8vDm/N8k20TnnOuk46TXnMt8t2iXHGsYSxA26CbQCsQCuAasDqwauC6wPqRKjE6AXoRunIaknmjmYPZtFmEuYT6BZqV6rYqtmqGuYd5Z+mJGalJ2WoZaqkcGRxJDGjcWJtmA=",
    aspect: 0.9089,
    spec: { seed: 30, length: "long", shape: "sprint" },
  },
  "alpine-4": {
    d: "Of857TbjN+E73j3aPtU90jrRNNAuzCfOCskJygfXBNgC1QHCCLwXnhmbHJshniefKaIoqiqtLa45pkGkRJxHmk+YVZlcll6SXI9Si1F/Un1UfFt+Xn1heGZ0ZnBkbWFtVHRRcU9pTGZCaD1rLmgtZi1jNFc5VT1YQFlLTUpLRUk/QjxCNkUxQipBJ0ImRCtMKFMpWCdeKGoqbTFuM3AyfjF/L38qeB9yHG4cZxVhFFkWUxxRHU8bPx00GzIAJQAiBR4HGAoWERUUDBkJHAUfAyUEKQEsAS8CMgU0Bj0CRAVMAFYEXwJiA2UJZwpwCXYOeg18Dn4RexiAI4MmkC2SK5IelB2ZHp8box2pI7MhtSG2JbMosyu1LrgwvjDCMsUyxi/EKcQl0x7VINUo2SzdLewr8jD3Mfov+ij/I/4Y+hj1HPEd1gk=",
    aspect: 1.0526,
    spec: { seed: 27, length: "xlong", shape: "sprint" },
  },
  "alpine-5": {
    d: "/8L/ef1y+GryZeph42DbYHx4dHlsdmZwZWxlaIZAiTWIK4AfdBRqD0wCRQA7ADMDLAkoECcXKB4sJDUsODE7OTo/N0UzSyxPH1UZXBhgGGUigiGIH4wbkA6VBpsBogCpDe8P8xT3Hfoo+S/1ZsF0u4O5k7yhwtn74//w/vr5/fb/8f/D",
    aspect: 0.7078,
    spec: { seed: 34, length: "medium", shape: "circuit" },
  },
  "alpine-6": {
    d: "mauZiJ2ApXrjXOZY5VbfU9BOwUypS5tIkUGPPo86kjaXM9Yb3hbiEeEM3AfUBMoCvgGmBZgFjQR9AXAAHg0YDxYRFhQjHSUgJyctLTsyYDhlOmY9YkFVRE5ITEtKU0RZBXcBegB9A4EMhT2FRYdJikuNS5BGlT+YKp4ioh2mGa0XvRjDG8ggzCjRMtVH2GXZct114Hbjbfdu+nT9hf+c+6n7xv/V/+f77vfx8/Lx8e7k5OLg4t3k2ejW+c/9zP/I/MP0v+m9wLu2vajGncaZw5mr",
    aspect: 0.4114,
    spec: { seed: 35, length: "long", shape: "circuit" },
  },
};
