#!/usr/bin/env node
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// THE STAGE BOXES' ROUTES — every campaign stage's road, as the shape the
// campaign menu draws in its box, built ahead of time and committed as
// data.
//
// The measurement that decided this: DRAWING a route is free and DERIVING
// one is not. Stroking a stage at thumbnail size costs under 7 ms;
// `compileStage` costs between 60 ms and ten SECONDS for the same stage
// (seed 5 at xlong is the ten), and twelve campaign levels are twelve
// seconds of it on a desktop. A menu that generated its own previews would
// open, freeze, and fill in a minute later on a phone.
//
// So only the expensive half happens here. What ships is a POLYLINE rather
// than a picture — a few hundred bytes a stage, into
// pwa/src/game/stage-routes.ts — and the menu strokes it as an SVG path at
// about a millisecond a box. That way the line is sharp at any size and
// takes the colour of the box it sits in, instead of being a picture of one
// state of one box.
//
// The banners behind a LOCATION are a different problem and a different
// tool: a country is many stages, so it gets a real render of the landscape
// rather than a map of any one road (scripts/biome-preview.mjs).
//
//   npm run routes
//
// The encoding itself is scripts/lib/stage-route.mjs, shared with
// tests/stage_preview_test.ts: this is generator output, so it goes stale
// the moment the rules move, and that test recompiles the two cheapest
// campaign stages and checks the committed bytes against them.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { aliasEngine } from "./lib/engine-alias.mjs";
import { routeOf } from "./lib/stage-route.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
aliasEngine(root);
const engine = await import(join(root, "engine/index.ts"));
const { DEFAULT_KNOBS, compileStage } = engine;
const { LOCATIONS } = await import(join(root, "pwa/src/game/campaign.ts"));

/** The generated module, written the way prettier would have written it so
 * that re-running this tool on a clean tree is a no-op.
 *
 * One field per line rather than an entry per line, which looks wasteful and
 * is not a choice: a route's base64 runs to several hundred characters, so
 * every entry is past the print width and prettier breaks all of them. An
 * emitter that writes the tidier one-liner just means `make fmt` rewrites
 * this file every time it is generated, and `make fmt-check` fails on any
 * branch that regenerated it without formatting afterwards. */
function routesModule(rows) {
  const entries = rows
    .map(
      ({ id, route, spec }) =>
        `  "${id}": {\n    d: "${route.d}",\n    aspect: ${route.aspect},\n` +
        `    spec: { seed: ${spec.seed}, length: "${spec.length}", shape: "${spec.shape}" },\n  },`,
    )
    .join("\n");
  return `// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// GENERATED by \`make routes\` (scripts/stage-routes.mjs). Do not edit.
//
// Every campaign stage's route, as the campaign menu draws it: the compiled
// centreline, simplified to within a pixel and quantised to a byte a
// coordinate. It is here as source rather than as a file to fetch because
// the whole campaign fits in a few kilobytes — cheaper to bundle than to
// ask the network for while a menu is already on screen.
//
// Regenerate whenever the generator's rules move: a stale route is a
// picture of a road nobody drives any more.

export type StageRoute = {
  /** The polyline, base64 of (x, y) byte pairs. 0 is the west and north
   * edge of the route's own bounding box, 255 the east and south. */
  d: string;
  /** How much wider than tall that bounding box is, in the world — what
   * the menu fits its drawing box to, so a stage keeps its shape. */
  aspect: number;
  /** THE ROAD THIS WAS DRAWN FROM. Nothing at runtime reads it; it is the
   * receipt, and \`tests/stage_preview_test.ts\` holds it against
   * \`campaign.ts\`. A level's seed or band edited without a
   * \`make previews\` leaves a picture of the road that USED to be there,
   * under the name of the one that is — and that is invisible unless the
   * data says which road it drew. */
  spec: { seed: number; length: string; shape: string };
};

export const STAGE_ROUTES: Record<string, StageRoute> = {
${entries}
};
`;
}

const routes = [];
for (const location of LOCATIONS) {
  const knobs = { ...DEFAULT_KNOBS, biome: location.biome };
  for (const level of location.levels) {
    const started = Date.now();
    const shape = level.shape ?? "sprint";
    const track = compileStage(level.seed, level.length, knobs, shape);
    const route = routeOf(track);
    routes.push({ id: level.id, route, spec: { seed: level.seed, length: level.length, shape } });
    console.log(
      `  ${level.id.padEnd(10)} ${(track.length / 1000).toFixed(1).padStart(5)} km  ` +
        `${String(route.points).padStart(4)} points  ` +
        `${String(route.d.length).padStart(4)} B  (${Date.now() - started} ms)`,
    );
  }
}

writeFileSync(join(root, "pwa/src/game/stage-routes.ts"), routesModule(routes));
const bytes = routes.reduce((sum, r) => sum + r.route.d.length, 0);
console.log(
  `\npwa/src/game/stage-routes.ts — ${routes.length} routes, ${(bytes / 1024).toFixed(1)} KB of polyline`,
);
